### ISSUE TITLE
运行example.py报错

### ISSUE THREAD

**Issue by sniperrich** [2061360308/NeteaseCloudMusic_PythonSDK#1]
![image](https://github.com/2061360308/NeteaseCloudMusic_PythonSDK/assets/110087661/49ffb8d1-bd49-4587-98de-ee0fabdc88d8)
输入啥都报错

**Comment by 2061360308** [comment]
好久没更新了，自从node接口作者github不更之后我就没在管过，这么长时间了网易云改接口啥的很正常的

**Comment by 2061360308** [comment]
你这个错误是js出错了，我不知道内部为啥会有这个问题，就是代码里面提示没有的那个是node原作者之前添加的一个token，为了不登陆的时候能调用基本接口，现在不知道为啥出错了

**Comment by 2061360308** [comment]
这个项目还是修修改改继续用的，但是吧，网易都严禁了，node接口作者那么多星最后还是废了。所以一点好处都没有，完全是当苦力一直随着网易云更新接口，还有被律师函的风险，所以想找人继续维护有点难。现实点的话还是自己用哪些接口就仿照这个代码搞一下。

**Comment by sniperrich** [comment]
好的，谢谢
